package intergraf;

import gertarefas.GerenciadorInterfaceGrafica;
import javax.swing.JOptionPane;
import modelo.Cliente;
import modelo.util.SexoEnum;
import org.hibernate.HibernateException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author thaly
 */
public class DialogCadastrarCliente extends javax.swing.JDialog {
    private GerenciadorInterfaceGrafica gerInterfaceGrafica;
    /**
     * Creates new form DialogCadastrarAdm
     */
    public DialogCadastrarCliente(java.awt.Frame parent, boolean modal, GerenciadorInterfaceGrafica gerInterfaceGrafica) {
        super(parent, modal);
        this.gerInterfaceGrafica = gerInterfaceGrafica;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoSexo = new javax.swing.ButtonGroup();
        painelCadastrarCliente = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        lblSexo = new javax.swing.JLabel();
        radioSexoMasculino = new javax.swing.JRadioButton();
        radioSexoFeminino = new javax.swing.JRadioButton();
        txtCPF = new javax.swing.JTextField();
        lblCPF = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        painelCadastrarCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 153, 255)), "Cadastrar Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 18), new java.awt.Color(51, 0, 255))); // NOI18N

        lblNome.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblNome.setText("Nome:");

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblEmail.setText("Email:");

        txtNome.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        btnSalvar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnVoltar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        lblSexo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblSexo.setText("Sexo:");

        grupoSexo.add(radioSexoMasculino);
        radioSexoMasculino.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        radioSexoMasculino.setSelected(true);
        radioSexoMasculino.setText("Masculino");

        grupoSexo.add(radioSexoFeminino);
        radioSexoFeminino.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        radioSexoFeminino.setText("Feminino");
        radioSexoFeminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSexoFemininoActionPerformed(evt);
            }
        });

        txtCPF.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPFActionPerformed(evt);
            }
        });

        lblCPF.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCPF.setText("CPF:");

        javax.swing.GroupLayout painelCadastrarClienteLayout = new javax.swing.GroupLayout(painelCadastrarCliente);
        painelCadastrarCliente.setLayout(painelCadastrarClienteLayout);
        painelCadastrarClienteLayout.setHorizontalGroup(
            painelCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastrarClienteLayout.createSequentialGroup()
                .addGroup(painelCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCadastrarClienteLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addGroup(painelCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelCadastrarClienteLayout.createSequentialGroup()
                                .addComponent(lblSexo)
                                .addGap(43, 43, 43)
                                .addComponent(radioSexoMasculino)
                                .addGap(77, 77, 77)
                                .addComponent(radioSexoFeminino))
                            .addGroup(painelCadastrarClienteLayout.createSequentialGroup()
                                .addGroup(painelCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNome)
                                    .addComponent(lblEmail)
                                    .addComponent(lblCPF))
                                .addGap(18, 18, 18)
                                .addGroup(painelCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(painelCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtNome)
                                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(painelCadastrarClienteLayout.createSequentialGroup()
                        .addGap(337, 337, 337)
                        .addComponent(btnSalvar)
                        .addGap(107, 107, 107)
                        .addComponent(btnVoltar)))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        painelCadastrarClienteLayout.setVerticalGroup(
            painelCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastrarClienteLayout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addGroup(painelCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(painelCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(painelCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSexo)
                    .addGroup(painelCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radioSexoMasculino)
                        .addComponent(radioSexoFeminino)))
                .addGroup(painelCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCadastrarClienteLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lblCPF))
                    .addGroup(painelCadastrarClienteLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(painelCadastrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnVoltar))
                .addContainerGap(316, Short.MAX_VALUE))
        );

        getContentPane().add(painelCadastrarCliente, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioSexoFemininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSexoFemininoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioSexoFemininoActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        gerInterfaceGrafica.fecharJanela(this);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void txtCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPFActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        Cliente cliente = new Cliente(0, txtNome.getText(), txtEmail.getText(), null, txtCPF.getText());
        if(radioSexoFeminino.isSelected())
        {
            cliente.setSexo(SexoEnum.F);     
        }
        else
        {
            cliente.setSexo(SexoEnum.M);
        }
        System.out.println(cliente.toString());
        try {
            gerInterfaceGrafica.getGerenciadorDominio().inserir(cliente);
            JOptionPane.showMessageDialog(this, "Cliente " + cliente.getId_usuario() + " inserido com sucesso!");
        } catch (HibernateException e) {
           JOptionPane.showMessageDialog(this, e);
        } 
    }//GEN-LAST:event_btnSalvarActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.ButtonGroup grupoSexo;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JPanel painelCadastrarCliente;
    private javax.swing.JRadioButton radioSexoFeminino;
    private javax.swing.JRadioButton radioSexoMasculino;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
