package intergraf;

import modelo.Produto;
import gertarefas.GerenciadorInterfaceGrafica;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import modelo.Categoria;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author thaly
 */
public class DialogCadastrarProduto extends javax.swing.JDialog {

    private GerenciadorInterfaceGrafica gerInterfaceGrafica;
    private Produto produtoSelecionado;

    /**
     * Creates new form DialogCadastrarProduto
     */
    public DialogCadastrarProduto(java.awt.Frame parent, boolean modal, GerenciadorInterfaceGrafica gerInterfaceGrafica) {
        super(parent, modal);
        this.gerInterfaceGrafica = gerInterfaceGrafica;
        produtoSelecionado = null;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelCadastrarProduto = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblPreco = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        lblCategoria = new javax.swing.JLabel();
        selectCategoria = new javax.swing.JComboBox<>();
        btnVoltar = new javax.swing.JButton();
        btnSalvarProduto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        painelCadastrarProduto.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 204, 255)), "Cadastrar Produto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(0, 0, 204))); // NOI18N
        painelCadastrarProduto.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                painelCadastrarProdutoComponentShown(evt);
            }
        });

        lblNome.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblNome.setText("Nome:");

        txtNome.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        lblPreco.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblPreco.setText("Preço");

        txtPreco.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        lblCategoria.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCategoria.setText("Categoria:");

        selectCategoria.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        selectCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione a categoria..." }));

        btnVoltar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnSalvarProduto.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnSalvarProduto.setText("Salvar");
        btnSalvarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelCadastrarProdutoLayout = new javax.swing.GroupLayout(painelCadastrarProduto);
        painelCadastrarProduto.setLayout(painelCadastrarProdutoLayout);
        painelCadastrarProdutoLayout.setHorizontalGroup(
            painelCadastrarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastrarProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCadastrarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCadastrarProdutoLayout.createSequentialGroup()
                        .addGroup(painelCadastrarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNome)
                            .addComponent(lblPreco))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painelCadastrarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                            .addComponent(txtPreco)))
                    .addGroup(painelCadastrarProdutoLayout.createSequentialGroup()
                        .addComponent(lblCategoria)
                        .addGap(18, 18, 18)
                        .addGroup(painelCadastrarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelCadastrarProdutoLayout.createSequentialGroup()
                                .addComponent(btnSalvarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(selectCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(400, Short.MAX_VALUE))
        );
        painelCadastrarProdutoLayout.setVerticalGroup(
            painelCadastrarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastrarProdutoLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(painelCadastrarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelCadastrarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPreco)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(painelCadastrarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoria)
                    .addComponent(selectCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(112, 112, 112)
                .addGroup(painelCadastrarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(270, Short.MAX_VALUE))
        );

        getContentPane().add(painelCadastrarProduto, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarProdutoActionPerformed
        if (produtoSelecionado != null) {
             try {
                 produtoSelecionado.setCategoria((Categoria) selectCategoria.getSelectedItem());
                 produtoSelecionado.setNome(txtNome.getText());
                 produtoSelecionado.setPreco(Double.parseDouble(txtPreco.getText()));
                gerInterfaceGrafica.getGerenciadorDominio().alterarProduto(produtoSelecionado);
                JOptionPane.showMessageDialog(this, "Produto alterado com sucessoo com sucesso!");
            } catch (ClassNotFoundException | SQLException e) {
                JOptionPane.showMessageDialog(this, e);
            }
        } else {
            Produto prod = new Produto(txtNome.getText(), Double.parseDouble(txtPreco.getText()), (Categoria) selectCategoria.getSelectedItem());

            try {
                gerInterfaceGrafica.getGerenciadorDominio().inserirProduto(prod);
                JOptionPane.showMessageDialog(this, "Produto " + prod.getId_produto() + " inserido com sucesso!");
            } catch (ClassNotFoundException | SQLException e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }

    }//GEN-LAST:event_btnSalvarProdutoActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        gerInterfaceGrafica.fecharJanela(this);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        gerInterfaceGrafica.carregarComboboxCategorias(selectCategoria);
        if (produtoSelecionado != null) {
            selectCategoria.setSelectedItem(produtoSelecionado.getCategoria());
            txtNome.setText(produtoSelecionado.getNome());
            txtPreco.setText(produtoSelecionado.getPreco().toString());
        }
    }//GEN-LAST:event_formComponentShown
    
    private void painelCadastrarProdutoComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_painelCadastrarProdutoComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_painelCadastrarProdutoComponentShown

    public Produto getProdutoSelecionado() {
        return produtoSelecionado;
    }

    public void setProdutoSelecionado(Produto produtoSelecionado) {
        this.produtoSelecionado = produtoSelecionado;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvarProduto;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JPanel painelCadastrarProduto;
    private javax.swing.JComboBox<String> selectCategoria;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPreco;
    // End of variables declaration//GEN-END:variables
}
