package intergraf;

import gertarefas.GerenciadorInterfaceGrafica;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ItemPedido;
import model.Pedido;
import model.Produto;
import modelo.util.FuncoesUteis;
import modelo.util.PagamentoEnum;
import org.hibernate.HibernateException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author thaly
 */
public class DialogVisualizarPedidos extends javax.swing.JDialog {

    private GerenciadorInterfaceGrafica gerInterfaceGrafica;
    private Pedido pedidoSelecionado;

    /**
     * Creates new form VisualizarProdutos
     */
    public DialogVisualizarPedidos(java.awt.Frame parent, boolean modal, GerenciadorInterfaceGrafica gerInterfaceGrafica) {
        super(parent, modal);
        this.gerInterfaceGrafica = gerInterfaceGrafica;
        this.pedidoSelecionado = null;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tableProdScroll = new javax.swing.JScrollPane();
        tablePedidos = new javax.swing.JTable();
        btnDetalhar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        lblCod = new javax.swing.JLabel();
        comboFiltroTipoPagamento = new javax.swing.JComboBox<>();
        lblPesqNome2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtFiltroDataInicio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFiltroDataFim = new javax.swing.JTextField();
        btnLimpar = new javax.swing.JButton();
        lblPesqNome3 = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        txFiltroCliente = new javax.swing.JTextField();
        spinnerFiltroCodigo = new javax.swing.JSpinner();
        btnPesquisarTodos = new javax.swing.JButton();
        checkBoxFiltroTipoPagamento = new javax.swing.JCheckBox();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 153, 255)), "Visualizar Pedidos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(0, 51, 255))); // NOI18N

        tablePedidos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        tablePedidos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tablePedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Cliente", "Data", "Tipo Pagamento", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableProdScroll.setViewportView(tablePedidos);

        btnDetalhar.setText("Detalhar Pedido");
        btnDetalhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalharActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnPesquisar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        lblCod.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCod.setText("Código:");

        comboFiltroTipoPagamento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblPesqNome2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPesqNome2.setText("Período:");

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel1.setText("De");

        txtFiltroDataInicio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel2.setText("a");

        txtFiltroDataFim.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtFiltroDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtFiltroDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFiltroDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtFiltroDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(41, 41, 41))
        );

        btnLimpar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        lblPesqNome3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPesqNome3.setText("Tipo Pagamento:");

        lblCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCliente.setText("Cliente:");

        txFiltroCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        spinnerFiltroCodigo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        spinnerFiltroCodigo.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        btnPesquisarTodos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPesquisarTodos.setText("Pesquisar Todos");
        btnPesquisarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarTodosActionPerformed(evt);
            }
        });

        checkBoxFiltroTipoPagamento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkBoxFiltroTipoPagamento.setText("Habilitar Filtro por Tipo de Pagamento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableProdScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 1070, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(btnDetalhar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(205, 205, 205))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(checkBoxFiltroTipoPagamento)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCod)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spinnerFiltroCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblPesqNome3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboFiltroTipoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lblPesqNome2)
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblCliente)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txFiltroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(btnPesquisar)
                        .addGap(26, 26, 26)
                        .addComponent(btnPesquisarTodos)
                        .addGap(39, 39, 39)
                        .addComponent(btnLimpar)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(comboFiltroTipoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblPesqNome3))
                            .addComponent(lblPesqNome2))))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCod)
                    .addComponent(lblCliente)
                    .addComponent(txFiltroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerFiltroCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPesquisar)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnLimpar)
                        .addComponent(btnPesquisarTodos)
                        .addComponent(checkBoxFiltroTipoPagamento)))
                .addGap(57, 57, 57)
                .addComponent(tableProdScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDetalhar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        gerInterfaceGrafica.fecharJanela(this);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        pesquisarTodos();
        try {
            List<PagamentoEnum> pagEnums = new ArrayList<>();
            pagEnums.add(PagamentoEnum.C);
            pagEnums.add(PagamentoEnum.D);
            pagEnums.add(PagamentoEnum.B);
            comboFiltroTipoPagamento.setModel(new DefaultComboBoxModel(pagEnums.toArray()));
        } catch (HibernateException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_formComponentShown

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        pesquisar();
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnPesquisarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarTodosActionPerformed
        pesquisarTodos();
    }//GEN-LAST:event_btnPesquisarTodosActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtFiltroDataFim.setText("");
        txtFiltroDataInicio.setText("");
        txFiltroCliente.setText("");
        spinnerFiltroCodigo.setValue(0);
        pesquisarTodos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnDetalharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalharActionPerformed
        int linhaSelecionada = tablePedidos.getSelectedRow();
        if (linhaSelecionada < 0) {
            JOptionPane.showMessageDialog(this, "Selecione um pedido!");
        } else {
            pedidoSelecionado = (Pedido) tablePedidos.getValueAt(linhaSelecionada, 0);
            setVisible(false);
            gerInterfaceGrafica.abrirDlgDetalharPedido(pedidoSelecionado);
            gerInterfaceGrafica.fecharJanela(this);
        }
    }//GEN-LAST:event_btnDetalharActionPerformed
    private void pesquisar() {
        String dataInicio = txtFiltroDataInicio.getText();
        String dataFim = txtFiltroDataFim.getText();
        Integer codigo = (Integer) spinnerFiltroCodigo.getValue();
        PagamentoEnum pagEnum = null;
        String cliente = null;
        if ((!FuncoesUteis.isValidDate(dataInicio)
                && !FuncoesUteis.isValidDate(dataFim))
                && (!dataInicio.isEmpty() && !dataFim.isEmpty())) {
            JOptionPane.showMessageDialog(this, "Preencha as data no formato dd/MM/yyyy!");
        } else {
            if (checkBoxFiltroTipoPagamento.isSelected()) {
                pagEnum = (PagamentoEnum) comboFiltroTipoPagamento.getSelectedItem();
            }
            if (!txFiltroCliente.getText().isEmpty()) {
                cliente = txFiltroCliente.getText();
            }
            try {
                // Resetando tabela
                ((DefaultTableModel) tablePedidos.getModel()).setRowCount(0);
                // Busca com filtros
                List<Pedido> pedidos = gerInterfaceGrafica.getGerenciadorDominio()
                        .pesquisarPedidos(pagEnum,
                                dataInicio,
                                dataFim,
                                codigo,
                                cliente
                        );
                pedidos.stream().forEach((p) -> {
                    inserePedidoTabela(p);
                });
            } catch (HibernateException e) {
                System.out.println(e.getMessage());
            }
        }

    }

    private void inserePedidoTabela(Pedido pedido)
    {
        ((DefaultTableModel) tablePedidos.getModel()).addRow(new Object[5]);
        int linhaAtual = tablePedidos.getRowCount() - 1;
        int i = 0;
        
        tablePedidos.setValueAt(pedido, linhaAtual, i++);
        tablePedidos.setValueAt(pedido.getCliente().getNome(), linhaAtual, i++);
        tablePedidos.setValueAt(FuncoesUteis.dateToStr(pedido.getDataPedido()), linhaAtual, i++);
        tablePedidos.setValueAt(pedido.getTipoPagamento(), linhaAtual, i++);
        tablePedidos.setValueAt(obterValorTotalPedido(pedido.getItensPedidos()), linhaAtual, i++);
    }
    private Double obterValorTotalPedido(List<ItemPedido> itens) {
        Double valorTotalPedido = 0d;
        for(ItemPedido item: itens)
        {
            valorTotalPedido += (item.getIdComposto().getProduto().getPreco() * item.getQuantidade());
        }
        return valorTotalPedido;
    }

    private void pesquisarTodos() {
        try {
            // Resetando tabela
            ((DefaultTableModel) tablePedidos.getModel()).setRowCount(0);
            // Busca com filtros
            List<Pedido> pedidos = gerInterfaceGrafica.getGerenciadorDominio()
                    .pesquisarPedidos(null,
                            null,
                            null,
                            null,
                            null
                    );
            pedidos.stream().forEach((p) -> {
                inserePedidoTabela(p);
            });
        } catch (HibernateException e) {
            System.out.println(e.getMessage());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalhar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnPesquisarTodos;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JCheckBox checkBoxFiltroTipoPagamento;
    private javax.swing.JComboBox<String> comboFiltroTipoPagamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblCod;
    private javax.swing.JLabel lblPesqNome2;
    private javax.swing.JLabel lblPesqNome3;
    private javax.swing.JSpinner spinnerFiltroCodigo;
    private javax.swing.JTable tablePedidos;
    private javax.swing.JScrollPane tableProdScroll;
    private javax.swing.JTextField txFiltroCliente;
    private javax.swing.JTextField txtFiltroDataFim;
    private javax.swing.JTextField txtFiltroDataInicio;
    // End of variables declaration//GEN-END:variables
}
