package intergraf;


import model.Produto;
import gertarefas.GerenciadorInterfaceGrafica;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Cliente;
import modelo.util.PagamentoEnum;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author thaly
 */
public class DialogRealizarPedido extends javax.swing.JDialog {
    private GerenciadorInterfaceGrafica gerInterfaceGrafica;
    private Produto prodSelecionado;
    private Cliente clienteSelecionado;
    
    public DialogRealizarPedido(java.awt.Frame parent, boolean modal, GerenciadorInterfaceGrafica gerInterfaceGrafica) {
        super(parent, modal);
        this.gerInterfaceGrafica = gerInterfaceGrafica;
        this.prodSelecionado = null;
        this.clienteSelecionado = null; 
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuPopUpExcluir = new javax.swing.JPopupMenu();
        menuExcluir = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        lblAddProdCarrinho = new javax.swing.JLabel();
        qtdPorProd = new javax.swing.JSpinner();
        lblQtd = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tableProdScroll = new javax.swing.JScrollPane();
        tableCarrinhoPedido = new javax.swing.JTable();
        btnRemoverItem = new javax.swing.JButton();
        btnFinalizarPedido = new javax.swing.JButton();
        lblTipoPagamento = new javax.swing.JLabel();
        selectTipoPagamento = new javax.swing.JComboBox<>();
        btnLimparCarrinho = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtValorTotalPedido = new javax.swing.JTextField();
        btnAdicionaAoCarrinho = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNomeProd = new javax.swing.JTextField();
        txtCategoriaProd = new javax.swing.JTextField();
        txtPrecoProd = new javax.swing.JTextField();
        btnBuscarProd = new javax.swing.JButton();
        lblAddProdCarrinho1 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        btnBuscarCliente = new javax.swing.JButton();

        menuExcluir.setText("Excluir");
        menuExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExcluirActionPerformed(evt);
            }
        });
        MenuPopUpExcluir.add(menuExcluir);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 255)), "Realizar Pedido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(51, 0, 204))); // NOI18N

        lblAddProdCarrinho.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblAddProdCarrinho.setText("Cliente:");

        qtdPorProd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        qtdPorProd.setModel(new javax.swing.SpinnerNumberModel(1, 1, 20, 1));

        lblQtd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblQtd.setText("Qtd:");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 255, 102)), "Carrinho", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(0, 255, 0))); // NOI18N

        tableCarrinhoPedido.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        tableCarrinhoPedido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tableCarrinhoPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Quantidade", "Categoria", "Valor Unitário", "Valor Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableCarrinhoPedido.setComponentPopupMenu(MenuPopUpExcluir);
        tableProdScroll.setViewportView(tableCarrinhoPedido);

        btnRemoverItem.setText("Remover item");
        btnRemoverItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverItemActionPerformed(evt);
            }
        });

        btnFinalizarPedido.setText("Finalizar Pedido");
        btnFinalizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarPedidoActionPerformed(evt);
            }
        });

        lblTipoPagamento.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTipoPagamento.setText("Selecione o tipo de pagamento:");

        selectTipoPagamento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        selectTipoPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectTipoPagamentoActionPerformed(evt);
            }
        });

        btnLimparCarrinho.setText("Limpar Carrinho");
        btnLimparCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCarrinhoActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("VALOR TOTAL DO PEDIDO:");

        txtValorTotalPedido.setEditable(false);
        txtValorTotalPedido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtValorTotalPedido.setForeground(new java.awt.Color(0, 204, 102));
        txtValorTotalPedido.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableProdScroll)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(btnRemoverItem, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(btnLimparCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(btnFinalizarPedido)
                        .addGap(43, 43, 43)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTipoPagamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(selectTipoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValorTotalPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(tableProdScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTipoPagamento)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(selectTipoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(txtValorTotalPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemoverItem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFinalizarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimparCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        btnAdicionaAoCarrinho.setText("Adicionar ao Carrinho");
        btnAdicionaAoCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionaAoCarrinhoActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setForeground(new java.awt.Color(153, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Preço:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Categoria:");

        txtNomeProd.setEditable(false);
        txtNomeProd.setBackground(new java.awt.Color(204, 204, 204));
        txtNomeProd.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        txtNomeProd.setForeground(new java.awt.Color(255, 255, 0));
        txtNomeProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeProdActionPerformed(evt);
            }
        });

        txtCategoriaProd.setEditable(false);
        txtCategoriaProd.setBackground(new java.awt.Color(204, 204, 204));
        txtCategoriaProd.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        txtCategoriaProd.setForeground(new java.awt.Color(255, 255, 0));
        txtCategoriaProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCategoriaProdActionPerformed(evt);
            }
        });

        txtPrecoProd.setEditable(false);
        txtPrecoProd.setBackground(new java.awt.Color(204, 204, 204));
        txtPrecoProd.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        txtPrecoProd.setForeground(new java.awt.Color(255, 255, 0));
        txtPrecoProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoProdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(txtNomeProd, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtCategoriaProd, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addComponent(txtPrecoProd, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(txtPrecoProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCategoriaProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtNomeProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        btnBuscarProd.setBackground(new java.awt.Color(234, 250, 255));
        btnBuscarProd.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnBuscarProd.setForeground(new java.awt.Color(0, 0, 153));
        btnBuscarProd.setText("Buscar Produto");
        btnBuscarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProdActionPerformed(evt);
            }
        });

        lblAddProdCarrinho1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblAddProdCarrinho1.setText("Adicione produtos ao carrinho:");

        txtCliente.setEditable(false);
        txtCliente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtCliente.setForeground(new java.awt.Color(0, 51, 255));

        btnBuscarCliente.setBackground(new java.awt.Color(234, 250, 255));
        btnBuscarCliente.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnBuscarCliente.setForeground(new java.awt.Color(0, 0, 153));
        btnBuscarCliente.setText("Buscar Cliente");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(31, 31, 31))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAdicionaAoCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblAddProdCarrinho)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCliente))
                            .addComponent(lblAddProdCarrinho1))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnBuscarProd)
                                .addGap(10, 10, 10)
                                .addComponent(lblQtd)
                                .addGap(18, 18, 18)
                                .addComponent(qtdPorProd, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnBuscarCliente))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddProdCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddProdCarrinho1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQtd)
                    .addComponent(qtdPorProd, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAdicionaAoCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionaAoCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionaAoCarrinhoActionPerformed
        if(this.prodSelecionado == null)
        {
            JOptionPane.showMessageDialog(this, "Selecione um produto!");
        }
        else if(produtoJaAdicionadoAoCarrinho(this.prodSelecionado))
        {
            JOptionPane.showMessageDialog(this, "Produto já adicionado ao carrinho!");
        }
        else
        {
            gerInterfaceGrafica.insereNaTabelaPedido(prodSelecionado, (Integer) qtdPorProd.getValue(), tableCarrinhoPedido);
        }
        txtValorTotalPedido.setText(String.valueOf(obterValorTotalPedido()));
    }//GEN-LAST:event_btnAdicionaAoCarrinhoActionPerformed
    private boolean produtoJaAdicionadoAoCarrinho(Produto prod)
    {
        for(int i = 0; i < tableCarrinhoPedido.getRowCount(); i++)
        {
            if(((Produto) tableCarrinhoPedido.getValueAt(i, 0)).getNome().equalsIgnoreCase(prod.getNome()))
            {
                return true;
            }
        }
        return false;
    }
    private void menuExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExcluirActionPerformed
        
    }//GEN-LAST:event_menuExcluirActionPerformed

    private void selectTipoPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectTipoPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectTipoPagamentoActionPerformed

    private void btnFinalizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarPedidoActionPerformed
        if(clienteSelecionado == null)
        {
            JOptionPane.showMessageDialog(this, "Selecione um cliente!");
        }
        else if(tableCarrinhoPedido.getRowCount() == 0)
        {
            JOptionPane.showMessageDialog(this, "Selecione ao menos um produto!");
        }
        else
        {
            int id_pedido = gerInterfaceGrafica
                                              .getGerenciadorDominio()
                                              .inserirPedido(clienteSelecionado, (PagamentoEnum) selectTipoPagamento.getSelectedItem(),tableCarrinhoPedido);
            JOptionPane.showMessageDialog(this, "Pedido " + id_pedido + " inserido com sucesso!");
            gerInterfaceGrafica.fecharJanela(this);
        }
        
    }//GEN-LAST:event_btnFinalizarPedidoActionPerformed
    private Double obterValorTotalPedido(){
        Double valorTotalPedido = 0d;
        for (int i = 0; i < tableCarrinhoPedido.getRowCount(); i++) {                
                valorTotalPedido += (Double) tableCarrinhoPedido.getValueAt(i, 4);
            }
        return valorTotalPedido;
    }
    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        gerInterfaceGrafica.fecharJanela(this);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnBuscarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProdActionPerformed
        gerInterfaceGrafica.abrirDlgVisualizarProdutos();
    }//GEN-LAST:event_btnBuscarProdActionPerformed

    private void txtPrecoProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoProdActionPerformed

    private void txtNomeProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeProdActionPerformed

    private void txtCategoriaProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCategoriaProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCategoriaProdActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        gerInterfaceGrafica.abrirDlgVisualizarClientes();
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        List<PagamentoEnum> list = new ArrayList<>();
        list.add(PagamentoEnum.D);
        list.add(PagamentoEnum.C);
        list.add(PagamentoEnum.B);
        selectTipoPagamento.setModel(new DefaultComboBoxModel(list.toArray()));
    }//GEN-LAST:event_formComponentShown

    private void btnLimparCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCarrinhoActionPerformed
        ((DefaultTableModel) tableCarrinhoPedido.getModel()).setRowCount(0);     
        txtValorTotalPedido.setText(String.valueOf(obterValorTotalPedido()));
    }//GEN-LAST:event_btnLimparCarrinhoActionPerformed

    private void btnRemoverItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverItemActionPerformed
        int linhaSelecionada = tableCarrinhoPedido.getSelectedRow();
        if(linhaSelecionada != -1)
        {
            ((DefaultTableModel) tableCarrinhoPedido.getModel()).removeRow(linhaSelecionada);
            txtValorTotalPedido.setText(String.valueOf(obterValorTotalPedido()));
        }
    }//GEN-LAST:event_btnRemoverItemActionPerformed
    public void carregarInfoProd() {
       if(this.prodSelecionado != null)
       {
           txtCategoriaProd.setText(prodSelecionado.getCategoria().getNome());
           txtNomeProd.setText(prodSelecionado.getNome());
           txtPrecoProd.setText("R$ " + String.valueOf(prodSelecionado.getPreco()));
       }
    }
    
    
    public void carregarInfoCliente() {
        if(this.clienteSelecionado != null)
        {
            txtCliente.setText(clienteSelecionado.getNome());
        }
    }

    public Produto getProdSelecionado() {
        return prodSelecionado;
    }

    public void setProdSelecionado(Produto prodSelecionado) {
        this.prodSelecionado = prodSelecionado;
    }

    public Cliente getClienteSelecionado() {
        return clienteSelecionado;
    }

    public void setClienteSelecionado(Cliente clienteSelecionado) {
        this.clienteSelecionado = clienteSelecionado;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu MenuPopUpExcluir;
    private javax.swing.JButton btnAdicionaAoCarrinho;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnBuscarProd;
    private javax.swing.JButton btnFinalizarPedido;
    private javax.swing.JButton btnLimparCarrinho;
    private javax.swing.JButton btnRemoverItem;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblAddProdCarrinho;
    private javax.swing.JLabel lblAddProdCarrinho1;
    private javax.swing.JLabel lblQtd;
    private javax.swing.JLabel lblTipoPagamento;
    private javax.swing.JMenuItem menuExcluir;
    private javax.swing.JSpinner qtdPorProd;
    private javax.swing.JComboBox<String> selectTipoPagamento;
    private javax.swing.JTable tableCarrinhoPedido;
    private javax.swing.JScrollPane tableProdScroll;
    private javax.swing.JTextField txtCategoriaProd;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtNomeProd;
    private javax.swing.JTextField txtPrecoProd;
    private javax.swing.JTextField txtValorTotalPedido;
    // End of variables declaration//GEN-END:variables

}
